// games.ts
// Big game database extracted into its own file

export const GAMES_DATABASE = [
  { id: 1, title: "The Last of Us", year: 2013, primaryGenre: "Action-Adventure", secondaryGenres: "Survival", thirdGenre: "Post-Apocalyptic", rating: 95, platforms: "PlayStation Store / Steam" },
  { id: 2, title: "Ghost of Tsushima", year: 2020, primaryGenre: "Action-Adventure", secondaryGenres: "Open-World/Sandbox", thirdGenre: "Stealth", rating: 87, platforms: "PlayStation Store / Steam" },
  { id: 3, title: "Detroit: Become Human", year: 2018, primaryGenre: "Adventure", secondaryGenres: "Interactive Movie", thirdGenre: "Plot with Many Endings", rating: 78, platforms: "PlayStation Store / Steam" },
  { id: 4, title: "Counter-Strike 2", year: 2023, primaryGenre: "Shooter", secondaryGenres: "Tactical", thirdGenre: "Competitive", rating: 80, platforms: "Steam" },
  { id: 5, title: "Call of Duty: Modern Warfare II", year: 2022, primaryGenre: "Shooter", secondaryGenres: "First-Person", thirdGenre: "Action", rating: 76, platforms: "Steam / Epic Games Store" },
  { id: 6, title: "Overwatch 2", year: 2022, primaryGenre: "Shooter", secondaryGenres: "Hero Shooter", thirdGenre: "Multiplayer", rating: 79, platforms: "Battle.net" },
  { id: 7, title: "Assassin's Creed Mirage", year: 2023, primaryGenre: "Action-Adventure", secondaryGenres: "Stealth", thirdGenre: "Open-World/Sandbox", rating: 77, platforms: "Ubisoft Connect / Epic Games Store" },
  { id: 8, title: "Assassin's Creed Valhalla", year: 2020, primaryGenre: "Action-Adventure", secondaryGenres: "Open-World/Sandbox", thirdGenre: "RPG", rating: 80, platforms: "Ubisoft Connect / Epic Games Store" },
  { id: 9, title: "Assassin's Creed Origins", year: 2017, primaryGenre: "Action-Adventure", secondaryGenres: "RPG", thirdGenre: "Open-World/Sandbox", rating: 84, platforms: "Steam / Ubisoft Connect" },
  { id: 10, title: "Red Dead Redemption 2", year: 2018, primaryGenre: "Action-Adventure", secondaryGenres: "Open-World/Sandbox", thirdGenre: "Western", rating: 96, platforms: "Steam / Rockstar Games Launcher" },
  { id: 11, title: "Grand Theft Auto V", year: 2013, primaryGenre: "Open-World/Sandbox", secondaryGenres: "Action-Adventure", thirdGenre: "Crime", rating: 97, platforms: "Steam / Rockstar Games Launcher" },
  { id: 12, title: "Elden Ring", year: 2022, primaryGenre: "RPG", secondaryGenres: "Soulsborne", thirdGenre: "Open-World/Sandbox", rating: 96, platforms: "Steam" },
  { id: 13, title: "Dark Souls III", year: 2016, primaryGenre: "RPG", secondaryGenres: "Soulsborne", thirdGenre: "Action", rating: 89, platforms: "Steam" },
  { id: 14, title: "Sekiro: Shadows Die Twice", year: 2019, primaryGenre: "Action-Adventure", secondaryGenres: "Soulsborne", thirdGenre: "Singleplayer", rating: 90, platforms: "Steam" },
  { id: 15, title: "Hades", year: 2018, primaryGenre: "Roguelike", secondaryGenres: "Action", thirdGenre: "Indie", rating: 93, platforms: "Steam / Epic Games Store" },
  { id: 16, title: "Honkai: Star Rail", year: 2023, primaryGenre: "RPG", secondaryGenres: "Turn-Based", thirdGenre: "Gacha", rating: 82, platforms: "Epic Games Store" },
  { id: 17, title: "Genshin Impact", year: 2020, primaryGenre: "RPG", secondaryGenres: "Open-World/Sandbox", thirdGenre: "Gacha", rating: 86, platforms: "Epic Games Store" },
  { id: 18, title: "Valorant", year: 2020, primaryGenre: "Shooter", secondaryGenres: "Tactical", thirdGenre: "Competitive", rating: 80, platforms: "Riot Client" },
  { id: 19, title: "League of Legends", year: 2009, primaryGenre: "MOBA", secondaryGenres: "Competitive", thirdGenre: "Team-Based", rating: 78, platforms: "Riot Client" },
  { id: 20, title: "Dota 2", year: 2013, primaryGenre: "MOBA", secondaryGenres: "Competitive", thirdGenre: "Team-Based", rating: 90, platforms: "Steam" },
  { id: 21, title: "Apex Legends", year: 2019, primaryGenre: "Shooter", secondaryGenres: "Battle Royale", thirdGenre: "Hero Shooter", rating: 88, platforms: "Steam / EA App" },
  { id: 22, title: "Fortnite", year: 2017, primaryGenre: "Shooter", secondaryGenres: "Battle Royale", thirdGenre: "Building", rating: 85, platforms: "Epic Games Store" },
  { id: 23, title: "Minecraft", year: 2011, primaryGenre: "Sandbox", secondaryGenres: "Survival", thirdGenre: "Creative", rating: 93, platforms: "Minecraft Launcher" },
  { id: 24, title: "Stardew Valley", year: 2016, primaryGenre: "Simulation", secondaryGenres: "Farming", thirdGenre: "Indie", rating: 89, platforms: "Steam / GOG" },
  { id: 25, title: "The Witcher 3: Wild Hunt", year: 2015, primaryGenre: "RPG", secondaryGenres: "Open-World/Sandbox", thirdGenre: "Fantasy", rating: 93, platforms: "Steam / GOG" },
  { id: 26, title: "Cyberpunk 2077", year: 2020, primaryGenre: "RPG", secondaryGenres: "Open-World/Sandbox", thirdGenre: "Sci-Fi", rating: 86, platforms: "Steam / GOG / Epic Games Store" },
  { id: 27, title: "Horizon Zero Dawn", year: 2017, primaryGenre: "Action-Adventure", secondaryGenres: "Open-World/Sandbox", thirdGenre: "Sci-Fi", rating: 89, platforms: "Steam / Epic Games Store" },
  { id: 28, title: "Horizon Forbidden West", year: 2022, primaryGenre: "Action-Adventure", secondaryGenres: "Open-World/Sandbox", thirdGenre: "Sci-Fi", rating: 88, platforms: "PlayStation Store" },
  { id: 29, title: "Forza Horizon 5", year: 2021, primaryGenre: "Racing", secondaryGenres: "Open-World/Sandbox", thirdGenre: "Simulation", rating: 92, platforms: "Steam / Microsoft Store" },
  { id: 30, title: "Gran Turismo 7", year: 2022, primaryGenre: "Racing", secondaryGenres: "Simulation", thirdGenre: "Sports", rating: 87, platforms: "PlayStation Store" },
  { id: 31, title: "FIFA 23", year: 2022, primaryGenre: "Sports", secondaryGenres: "Football/Soccer", thirdGenre: "Multiplayer", rating: 79, platforms: "Steam / EA App" },
  { id: 32, title: "NBA 2K24", year: 2023, primaryGenre: "Sports", secondaryGenres: "Basketball", thirdGenre: "Multiplayer", rating: 72, platforms: "Steam" },
  { id: 33, title: "Madden NFL 24", year: 2023, primaryGenre: "Sports", secondaryGenres: "American Football", thirdGenre: "Simulation", rating: 68, platforms: "Steam / EA App" },
  { id: 34, title: "The Sims 4", year: 2014, primaryGenre: "Simulation", secondaryGenres: "Life Simulation", thirdGenre: "Creative", rating: 70, platforms: "Steam / EA App" },
  { id: 35, title: "Cities: Skylines", year: 2015, primaryGenre: "Simulation", secondaryGenres: "City Builder", thirdGenre: "Strategy", rating: 85, platforms: "Steam" },
  { id: 36, title: "Civilization VI", year: 2016, primaryGenre: "Strategy", secondaryGenres: "Turn-Based", thirdGenre: "4X", rating: 88, platforms: "Steam / Epic Games Store" },
  { id: 37, title: "Total War: Warhammer III", year: 2022, primaryGenre: "Strategy", secondaryGenres: "RTS", thirdGenre: "Turn-Based", rating: 86, platforms: "Steam / Epic Games Store" },
  { id: 38, title: "Starcraft II", year: 2010, primaryGenre: "RTS", secondaryGenres: "Sci-Fi", thirdGenre: "Competitive", rating: 93, platforms: "Battle.net" },
  { id: 39, title: "World of Warcraft", year: 2004, primaryGenre: "MMORPG", secondaryGenres: "Fantasy", thirdGenre: "Online", rating: 89, platforms: "Battle.net" },
  { id: 40, title: "Final Fantasy XIV", year: 2013, primaryGenre: "MMORPG", secondaryGenres: "Fantasy", thirdGenre: "Online", rating: 89, platforms: "Steam / Square Enix Launcher" },
  { id: 41, title: "Path of Exile", year: 2013, primaryGenre: "RPG", secondaryGenres: "Action", thirdGenre: "Online", rating: 86, platforms: "Steam" },
  { id: 42, title: "Diablo IV", year: 2023, primaryGenre: "RPG", secondaryGenres: "Action", thirdGenre: "Online", rating: 85, platforms: "Battle.net" },
  { id: 43, title: "Lost Ark", year: 2019, primaryGenre: "MMORPG", secondaryGenres: "Action", thirdGenre: "Online", rating: 81, platforms: "Steam" },
  { id: 44, title: "Terraria", year: 2011, primaryGenre: "Sandbox", secondaryGenres: "Adventure", thirdGenre: "Survival", rating: 91, platforms: "Steam" },
  { id: 45, title: "Don't Starve Together", year: 2016, primaryGenre: "Survival", secondaryGenres: "Co-op", thirdGenre: "Indie", rating: 82, platforms: "Steam" },
  { id: 46, title: "Rust", year: 2018, primaryGenre: "Survival", secondaryGenres: "Multiplayer", thirdGenre: "Sandbox", rating: 76, platforms: "Steam" },
  { id: 47, title: "ARK: Survival Evolved", year: 2017, primaryGenre: "Survival", secondaryGenres: "Open-World/Sandbox", thirdGenre: "Dinosaur", rating: 70, platforms: "Steam / Epic Games Store" },
  { id: 48, title: "Subnautica", year: 2018, primaryGenre: "Survival", secondaryGenres: "Adventure", thirdGenre: "Underwater", rating: 87, platforms: "Steam / Epic Games Store" },
  { id: 49, title: "No Man's Sky", year: 2016, primaryGenre: "Adventure", secondaryGenres: "Exploration", thirdGenre: "Sci-Fi", rating: 78, platforms: "Steam" },
  { id: 50, title: "Factorio", year: 2020, primaryGenre: "Simulation", secondaryGenres: "Automation", thirdGenre: "Strategy", rating: 91, platforms: "Steam" },
  { id: 51, title: "Satisfactory", year: 2020, primaryGenre: "Simulation", secondaryGenres: "Automation", thirdGenre: "First-Person", rating: 85, platforms: "Steam / Epic Games Store" },
  { id: 52, title: "RimWorld", year: 2018, primaryGenre: "Simulation", secondaryGenres: "Colony Sim", thirdGenre: "Strategy", rating: 87, platforms: "Steam" },
  { id: 53, title: "Crusader Kings III", year: 2020, primaryGenre: "Strategy", secondaryGenres: "Grand Strategy", thirdGenre: "Simulation", rating: 91, platforms: "Steam" },
  { id: 54, title: "Europa Universalis IV", year: 2013, primaryGenre: "Strategy", secondaryGenres: "Grand Strategy", thirdGenre: "Historical", rating: 87, platforms: "Steam" },
  { id: 55, title: "Hearts of Iron IV", year: 2016, primaryGenre: "Strategy", secondaryGenres: "Grand Strategy", thirdGenre: "War", rating: 83, platforms: "Steam" },
  { id: 56, title: "Planet Zoo", year: 2019, primaryGenre: "Simulation", secondaryGenres: "Management", thirdGenre: "Building", rating: 81, platforms: "Steam" },
  { id: 57, title: "Planet Coaster", year: 2016, primaryGenre: "Simulation", secondaryGenres: "Management", thirdGenre: "Building", rating: 84, platforms: "Steam" },
  { id: 58, title: "RollerCoaster Tycoon Classic", year: 2016, primaryGenre: "Simulation", secondaryGenres: "Management", thirdGenre: "Building", rating: 85, platforms: "Steam / Mobile" },
  { id: 59, title: "Age of Empires IV", year: 2021, primaryGenre: "RTS", secondaryGenres: "Historical", thirdGenre: "Strategy", rating: 81, platforms: "Steam / Microsoft Store" },
  { id: 60, title: "Age of Empires II: Definitive Edition", year: 2019, primaryGenre: "RTS", secondaryGenres: "Historical", thirdGenre: "Strategy", rating: 90, platforms: "Steam / Microsoft Store" },
  { id: 61, title: "Halo Infinite", year: 2021, primaryGenre: "Shooter", secondaryGenres: "Sci-Fi", thirdGenre: "Multiplayer", rating: 80, platforms: "Steam / Microsoft Store" },
  { id: 62, title: "DOOM Eternal", year: 2020, primaryGenre: "Shooter", secondaryGenres: "Action", thirdGenre: "Singleplayer", rating: 90, platforms: "Steam" },
  { id: 63, title: "Far Cry 6", year: 2021, primaryGenre: "Shooter", secondaryGenres: "Open-World/Sandbox", thirdGenre: "Action", rating: 75, platforms: "Ubisoft Connect / Epic Games Store" },
  { id: 64, title: "Borderlands 3", year: 2019, primaryGenre: "Shooter", secondaryGenres: "Looter Shooter", thirdGenre: "Co-op", rating: 81, platforms: "Steam / Epic Games Store" },
  { id: 65, title: "Destiny 2", year: 2017, primaryGenre: "Shooter", secondaryGenres: "Looter Shooter", thirdGenre: "Online", rating: 83, platforms: "Steam" },
  { id: 66, title: "Rainbow Six Siege", year: 2015, primaryGenre: "Shooter", secondaryGenres: "Tactical", thirdGenre: "Competitive", rating: 82, platforms: "Steam / Ubisoft Connect" },
  { id: 67, title: "Warframe", year: 2013, primaryGenre: "Shooter", secondaryGenres: "Looter Shooter", thirdGenre: "Online", rating: 78, platforms: "Steam" },
  { id: 68, title: "Monster Hunter: World", year: 2018, primaryGenre: "RPG", secondaryGenres: "Action", thirdGenre: "Co-op", rating: 90, platforms: "Steam" },
  { id: 69, title: "Monster Hunter Rise", year: 2021, primaryGenre: "RPG", secondaryGenres: "Action", thirdGenre: "Co-op", rating: 88, platforms: "Steam" },
  { id: 70, title: "Pokémon Legends: Arceus", year: 2022, primaryGenre: "RPG", secondaryGenres: "Adventure", thirdGenre: "Creature Collection", rating: 83, platforms: "Nintendo Switch" },
  { id: 71, title: "Pokémon Scarlet/Violet", year: 2022, primaryGenre: "RPG", secondaryGenres: "Adventure", thirdGenre: "Creature Collection", rating: 72, platforms: "Nintendo Switch" },
  { id: 72, title: "Super Mario Odyssey", year: 2017, primaryGenre: "Platformer", secondaryGenres: "Adventure", thirdGenre: "3D Platformer", rating: 97, platforms: "Nintendo Switch" },
  { id: 73, title: "The Legend of Zelda: Breath of the Wild", year: 2017, primaryGenre: "Action-Adventure", secondaryGenres: "Open-World/Sandbox", thirdGenre: "Fantasy", rating: 97, platforms: "Nintendo Switch" },
  { id: 74, title: "The Legend of Zelda: Tears of the Kingdom", year: 2023, primaryGenre: "Action-Adventure", secondaryGenres: "Open-World/Sandbox", thirdGenre: "Fantasy", rating: 96, platforms: "Nintendo Switch" },
  { id: 75, title: "Celeste", year: 2018, primaryGenre: "Platformer", secondaryGenres: "Indie", thirdGenre: "Precision Platformer", rating: 94, platforms: "Steam / Nintendo Switch" },
  { id: 76, title: "Hollow Knight", year: 2017, primaryGenre: "Metroidvania", secondaryGenres: "Indie", thirdGenre: "Action", rating: 90, platforms: "Steam / Nintendo Switch" },
  { id: 77, title: "Ori and the Blind Forest", year: 2015, primaryGenre: "Platformer", secondaryGenres: "Metroidvania", thirdGenre: "Indie", rating: 88, platforms: "Steam / Microsoft Store" },
  { id: 78, title: "Ori and the Will of the Wisps", year: 2020, primaryGenre: "Platformer", secondaryGenres: "Metroidvania", thirdGenre: "Indie", rating: 90, platforms: "Steam / Microsoft Store" },
  { id: 79, title: "Cuphead", year: 2017, primaryGenre: "Platformer", secondaryGenres: "Run and Gun", thirdGenre: "Indie", rating: 88, platforms: "Steam / GOG" },
  { id: 80, title: "Dead Cells", year: 2018, primaryGenre: "Roguelike", secondaryGenres: "Metroidvania", thirdGenre: "Action", rating: 89, platforms: "Steam / Nintendo Switch" },
  { id: 81, title: "Slay the Spire", year: 2019, primaryGenre: "Roguelike", secondaryGenres: "Deckbuilder", thirdGenre: "Indie", rating: 89, platforms: "Steam / Nintendo Switch" },
  { id: 82, title: "Inscryption", year: 2021, primaryGenre: "Card Game", secondaryGenres: "Puzzle", thirdGenre: "Horror", rating: 85, platforms: "Steam" },
  { id: 83, title: "Return of the Obra Dinn", year: 2018, primaryGenre: "Puzzle", secondaryGenres: "Mystery", thirdGenre: "Indie", rating: 89, platforms: "Steam" },
  { id: 84, title: "Outer Wilds", year: 2019, primaryGenre: "Adventure", secondaryGenres: "Exploration", thirdGenre: "Sci-Fi", rating: 92, platforms: "Steam / Epic Games Store" },
  { id: 85, title: "Disco Elysium", year: 2019, primaryGenre: "RPG", secondaryGenres: "Narrative", thirdGenre: "Isometric", rating: 95, platforms: "Steam / GOG" },
  { id: 86, title: "Baldur's Gate 3", year: 2023, primaryGenre: "RPG", secondaryGenres: "Turn-Based", thirdGenre: "Fantasy", rating: 96, platforms: "Steam / GOG" },
  { id: 87, title: "Lies of P", year: 2023, primaryGenre: "RPG", secondaryGenres: "Soulsborne", thirdGenre: "Action", rating: 83, platforms: "Steam" },
  { id: 88, title: "Wo Long: Fallen Dynasty", year: 2023, primaryGenre: "RPG", secondaryGenres: "Soulsborne", thirdGenre: "Action", rating: 78, platforms: "Steam" },
  { id: 89, title: "Remnant II", year: 2023, primaryGenre: "Shooter", secondaryGenres: "Soulsborne", thirdGenre: "Co-op", rating: 80, platforms: "Steam" },
  { id: 90, title: "The Division 2", year: 2019, primaryGenre: "Shooter", secondaryGenres: "Looter Shooter", thirdGenre: "Co-op", rating: 82, platforms: "Steam / Ubisoft Connect" },
  { id: 91, title: "Alan Wake 2", year: 2023, primaryGenre: "Horror", secondaryGenres: "Adventure", thirdGenre: "Narrative", rating: 89, platforms: "Epic Games Store" },
  { id: 92, title: "Resident Evil 4 Remake", year: 2023, primaryGenre: "Horror", secondaryGenres: "Action", thirdGenre: "Survival", rating: 93, platforms: "Steam" },
  { id: 93, title: "Resident Evil Village", year: 2021, primaryGenre: "Horror", secondaryGenres: "Action", thirdGenre: "Survival", rating: 84, platforms: "Steam" },
  { id: 94, title: "Dead Space Remake", year: 2023, primaryGenre: "Horror", secondaryGenres: "Action", thirdGenre: "Sci-Fi", rating: 89, platforms: "Steam / EA App" },
  { id: 95, title: "Silent Hill 2 Remake", year: 2024, primaryGenre: "Horror", secondaryGenres: "Psychological", thirdGenre: "Story-Driven", rating: 82, platforms: "Steam / PlayStation Store" },
  { id: 96, title: "HITMAN World of Assassination", year: 2022, primaryGenre: "Stealth", secondaryGenres: "Action", thirdGenre: "Sandbox", rating: 88, platforms: "Steam / Epic Games Store" },
  { id: 97, title: "Metal Gear Solid V: The Phantom Pain", year: 2015, primaryGenre: "Stealth", secondaryGenres: "Action-Adventure", thirdGenre: "Open-World/Sandbox", rating: 91, platforms: "Steam" },
  { id: 98, title: "Dishonored 2", year: 2016, primaryGenre: "Stealth", secondaryGenres: "Action-Adventure", thirdGenre: "Immersive Sim", rating: 88, platforms: "Steam" },
  { id: 99, title: "Prey (2017)", year: 2017, primaryGenre: "Shooter", secondaryGenres: "Immersive Sim", thirdGenre: "Sci-Fi", rating: 84, platforms: "Steam" },
  { id: 100, title: "Black Myth: Wukong", year: 2024, primaryGenre: "Action-Adventure", secondaryGenres: "Soulsborne", thirdGenre: "Fantasy", rating: 88, platforms: "Steam / Epic Games Store" },
  { id: 101, title: "Clash Royale", year: 2016, primaryGenre: "Strategy", secondaryGenres: "Card Game", thirdGenre: "Real-Time", rating: 85, platforms: "Google Play / App Store" },
  { id: 102, title: "Clash of Clans", year: 2012, primaryGenre: "Strategy", secondaryGenres: "Base Builder", thirdGenre: "Multiplayer", rating: 83, platforms: "Google Play / App Store" },
  { id: 103, title: "Brawl Stars", year: 2018, primaryGenre: "Shooter", secondaryGenres: "MOBA", thirdGenre: "Arcade", rating: 82, platforms: "Google Play / App Store" },
  { id: 104, title: "PUBG Mobile", year: 2018, primaryGenre: "Shooter", secondaryGenres: "Battle Royale", thirdGenre: "Mobile", rating: 78, platforms: "Google Play / App Store" },
  { id: 105, title: "Call of Duty: Mobile", year: 2019, primaryGenre: "Shooter", secondaryGenres: "Action", thirdGenre: "Mobile", rating: 81, platforms: "Google Play / App Store" },
  { id: 106, title: "Mobile Legends: Bang Bang", year: 2016, primaryGenre: "MOBA", secondaryGenres: "Action", thirdGenre: "Multiplayer", rating: 80, platforms: "Google Play / App Store" },
  { id: 107, title: "League of Legends: Wild Rift", year: 2020, primaryGenre: "MOBA", secondaryGenres: "Action", thirdGenre: "Mobile", rating: 83, platforms: "Google Play / App Store" },
  { id: 108, title: "Among Us", year: 2018, primaryGenre: "Party", secondaryGenres: "Social Deduction", thirdGenre: "Multiplayer", rating: 80, platforms: "Steam / Google Play / App Store" },
  { id: 109, title: "Candy Crush Saga", year: 2012, primaryGenre: "Puzzle", secondaryGenres: "Match-3", thirdGenre: "Casual", rating: 75, platforms: "Google Play / App Store" },
  { id: 110, title: "Subway Surfers", year: 2012, primaryGenre: "Arcade", secondaryGenres: "Endless Runner", thirdGenre: "Casual", rating: 78, platforms: "Google Play / App Store" },
  { id: 111, title: "Temple Run 2", year: 2013, primaryGenre: "Arcade", secondaryGenres: "Endless Runner", thirdGenre: "Casual", rating: 76, platforms: "Google Play / App Store" },
  { id: 112, title: "8 Ball Pool", year: 2010, primaryGenre: "Sports", secondaryGenres: "Billiards", thirdGenre: "Casual", rating: 80, platforms: "Google Play / App Store" },
  { id: 113, title: "FIFA Mobile", year: 2016, primaryGenre: "Sports", secondaryGenres: "Football/Soccer", thirdGenre: "Mobile", rating: 73, platforms: "Google Play / App Store" },
  { id: 114, title: "Asphalt 9: Legends", year: 2018, primaryGenre: "Racing", secondaryGenres: "Arcade", thirdGenre: "Mobile", rating: 81, platforms: "Google Play / App Store" },
  { id: 115, title: "Genshin Impact (Mobile)", year: 2020, primaryGenre: "RPG", secondaryGenres: "Open-World/Sandbox", thirdGenre: "Gacha", rating: 86, platforms: "Google Play / App Store" },
  { id: 116, title: "Honkai: Star Rail (Mobile)", year: 2023, primaryGenre: "RPG", secondaryGenres: "Turn-Based", thirdGenre: "Gacha", rating: 82, platforms: "Google Play / App Store" },
  { id: 117, title: "Royal Match", year: 2021, primaryGenre: "Puzzle", secondaryGenres: "Match-3", thirdGenre: "Casual", rating: 78, platforms: "Google Play / App Store" },
  { id: 118, title: "Roblox", year: 2006, primaryGenre: "Sandbox", secondaryGenres: "User-Generated", thirdGenre: "Online", rating: 80, platforms: "Google Play / App Store / PC" },
  { id: 119, title: "Hay Day", year: 2012, primaryGenre: "Simulation", secondaryGenres: "Farming", thirdGenre: "Casual Farming", rating: 80, platforms: "Google Play / App Store" },
];
